use project_x;

delete from event where event_id > 0;

insert into event (event_id, name, location) values (1001, 'Oxygen', 'Alegrete');
insert into event (event_id, name, location) values (1002, 'Adapalene', 'Münster');
insert into event (event_id, name, location) values (1003, 'Hemorrhoid Control', 'Předměřice nad Labem');
insert into event (event_id, name, location) values (1004, 'Equate nicotine', 'Qā’en');
insert into event (event_id, name, location) values (1005, 'Sweet Grape Antibacterial Hand', 'Nikolayevskaya');
insert into event (event_id, name, location) values (1006, 'Diltiazem Hydrochloride', 'Toledo');
insert into event (event_id, name, location) values (1007, 'Musculus deltoideus comp. 8 Special Order', 'Kardhiq');
insert into event (event_id, name, location) values (1008, 'CLARINS Ever Matte Broad Spectrum SPF 15 Tint 113', 'Datang');
insert into event (event_id, name, location) values (1009, 'topcare cold', 'Colombes');
insert into event (event_id, name, location) values (1010, 'Nighttime Cold and Flu', 'Kamyshevka Vtoraya');
insert into event (event_id, name, location) values (1011, 'CVS OIL FREE SPF 15', 'Qabqir');
insert into event (event_id, name, location) values (1012, 'Headache', 'Misasi');
insert into event (event_id, name, location) values (1013, 'Clonidine Hydrochloride', 'Linköping');
insert into event (event_id, name, location) values (1014, 'Capture Totale Radiance Restoring Serum Foundation SPF 15 040', 'Bakulong');
insert into event (event_id, name, location) values (1015, 'IRIS', 'Nerekhta');
insert into event (event_id, name, location) values (1016, 'SHISEIDO SHEER MATIFYING COMPACT (REFILL)', 'Cidadap');
insert into event (event_id, name, location) values (1017, 'Gelato APF', 'Pilar');
insert into event (event_id, name, location) values (1018, 'ISENTRESS', 'Anyuan');
insert into event (event_id, name, location) values (1019, 'Rimmel London', 'Zhuhong');
insert into event (event_id, name, location) values (1020, 'Night Time Cherry', 'Bachowice');
insert into event (event_id, name, location) values (1021, 'Purmist', 'Slatina');
insert into event (event_id, name, location) values (1022, 'members mark famotidine', 'Cam Lâm');
insert into event (event_id, name, location) values (1023, 'Cefadroxil', 'Calapan');
insert into event (event_id, name, location) values (1024, 'NIFEDIPINE', 'New Leyte');
insert into event (event_id, name, location) values (1025, 'Phenytoin Sodium', 'Jovellanos');
insert into event (event_id, name, location) values (1026, 'Gas-X', 'Vaasa');
insert into event (event_id, name, location) values (1027, 'Rizatriptan Benzoate', 'Baleagung');
insert into event (event_id, name, location) values (1028, 'MoistureWorx', 'Chengnan');
insert into event (event_id, name, location) values (1029, '09 Balancing Foundation', 'Al Jumaylīyah');
insert into event (event_id, name, location) values (1030, 'Lufyllin', 'Oropesa');
insert into event (event_id, name, location) values (1031, 'Buspirone Hydrochloride', 'Mingelchaur');
insert into event (event_id, name, location) values (1032, 'ROPINIROLE HYDROCHLORIDE', 'La Ravoire');
insert into event (event_id, name, location) values (1033, 'Purgo Satin Foam', 'Lattes');
insert into event (event_id, name, location) values (1034, 'BioTPres', 'Ourentã');
insert into event (event_id, name, location) values (1035, 'VITAMIN E DAY', 'Jiaotang');
insert into event (event_id, name, location) values (1036, 'Long-Lasting Oil-Free Moisturizer', 'Ma Đa Gui');
insert into event (event_id, name, location) values (1037, 'Extra Strength Pain Reliever PM', 'Przesmyki');
insert into event (event_id, name, location) values (1038, 'Acetazolamide', 'Purísima');
insert into event (event_id, name, location) values (1039, 'Eszopiclone', 'Xiyang');
insert into event (event_id, name, location) values (1040, 'CLINIMIX E', 'Krzynowłoga Mała');
insert into event (event_id, name, location) values (1041, 'Sorbitol-Mannitol', 'Sunbu');
insert into event (event_id, name, location) values (1042, 'Dr. Richs Numbing', 'Massenya');
insert into event (event_id, name, location) values (1043, 'Midazolam Hydrochloride', 'Guimarães');
insert into event (event_id, name, location) values (1044, 'Instant Hand Sanitizer', 'Yangxiang');
insert into event (event_id, name, location) values (1045, 'Eve Lom Radiance Perfected Tinted Moisturiser Broad Spectrum SPF 15 Sunscreen', 'Pavia');
insert into event (event_id, name, location) values (1046, 'FENTANYL CITRATE', 'Gardutanjak');
insert into event (event_id, name, location) values (1047, 'Anti-Blemish Foundation Primer Acne Treatment Gel', 'Belén de Umbría');
insert into event (event_id, name, location) values (1048, 'Lamivudine and Zidovudine', 'Čáslav');
insert into event (event_id, name, location) values (1049, 'Ibuprofen', 'Katoro');
insert into event (event_id, name, location) values (1050, 'Norpace', 'Mae Fa Luang');
insert into event (event_id, name, location) values (1051, 'Coldcalm', 'Gongchang');
insert into event (event_id, name, location) values (1052, 'Simvastatin', 'Sindangbarang');
insert into event (event_id, name, location) values (1053, 'Hydroxychloroquine Sulfate', 'Guihuaquan');
insert into event (event_id, name, location) values (1054, 'simply right nicotine', 'Providencia');
insert into event (event_id, name, location) values (1055, 'MERREM', 'Sumbergebang');
insert into event (event_id, name, location) values (1056, 'Felodipine', 'Bahía Blanca');
insert into event (event_id, name, location) values (1057, 'MENOPAUSE', 'Štore');
insert into event (event_id, name, location) values (1058, 'Levothyroxine Sodium', 'Shanglu');
insert into event (event_id, name, location) values (1059, 'Visipaque', 'Cravinhos');
insert into event (event_id, name, location) values (1060, 'Amerfresh Medicated', 'Sūrīān');
insert into event (event_id, name, location) values (1061, 'PreviDent', 'Santo Domingo');
insert into event (event_id, name, location) values (1062, 'Pollens - Weeds, Kochia scoparia', 'Longgang');
insert into event (event_id, name, location) values (1063, 'Care One Medicated Lip Balm in a Pot', 'Yunluo');
insert into event (event_id, name, location) values (1064, 'Oxazepam', 'Goyang-si');
insert into event (event_id, name, location) values (1065, 'Extravagant', 'Zhangdan');
insert into event (event_id, name, location) values (1066, 'Walgreens SunscreenSPF 70', 'Ołpiny');
insert into event (event_id, name, location) values (1067, 'Tears Naturale II Polyquad', 'Argelia');
insert into event (event_id, name, location) values (1068, 'Bio Viscum Phase', 'Ryczów');
insert into event (event_id, name, location) values (1069, 'ARNICA MONTANA', 'Kraśniczyn');
insert into event (event_id, name, location) values (1070, 'Neutrogena Healthy Skin 3 in 1 Concealer for Eyes', 'General Levalle');
insert into event (event_id, name, location) values (1071, 'Lantiseptic', 'Xinshi');
insert into event (event_id, name, location) values (1072, 'Compro', 'Tangqian');
insert into event (event_id, name, location) values (1073, 'Lovastatin', 'Pueblo Nuevo');
insert into event (event_id, name, location) values (1074, 'Diltiazem Hydrochloride', 'Zuolan');
insert into event (event_id, name, location) values (1075, 'Potassium Chloride', 'Catamayo');
insert into event (event_id, name, location) values (1076, 'Zonisamide', 'Dushi');
insert into event (event_id, name, location) values (1077, 'Aurum Hypericum Overwhelm Relief', 'Kandy');
insert into event (event_id, name, location) values (1078, 'Gly-Oxide', 'Doushan');
insert into event (event_id, name, location) values (1079, 'ATOPALM MOISTURIZING MUSCLE RUB', 'Novokayakent');
insert into event (event_id, name, location) values (1080, 'LBEL', 'Yelizavetinskaya');
insert into event (event_id, name, location) values (1081, 'Western Ragweed', 'Morelos');
insert into event (event_id, name, location) values (1082, 'TOLMETIN SODIUM', 'Aubervilliers');
insert into event (event_id, name, location) values (1083, 'IMITREX', 'Vorontsovka');
insert into event (event_id, name, location) values (1084, 'BUPAP', 'Novyye Cherëmushki');
insert into event (event_id, name, location) values (1085, 'equaline miconazole 1', 'Berlin');
insert into event (event_id, name, location) values (1086, 'Treatment Set TS331977', 'Perstorp');
insert into event (event_id, name, location) values (1087, 'JUNIOR STRENGTH ADVIL', 'Luoshe');
insert into event (event_id, name, location) values (1088, 'Levetiracetam', 'Energodar');
insert into event (event_id, name, location) values (1089, 'topcare miconazole 1', 'Palca');
insert into event (event_id, name, location) values (1090, 'Chlordiazepoxide and Amitriptyline Hydrochloride', 'Acopampa');
insert into event (event_id, name, location) values (1091, 'RHODOTORULA RUBRA', 'Tayāsīr');
insert into event (event_id, name, location) values (1092, 'Instant Hand Sanitizer with Moisturizers Unscented', 'Fuli');
insert into event (event_id, name, location) values (1093, 'Acne', 'Gajiram');
insert into event (event_id, name, location) values (1094, 'Coffea cruda', 'Sterlitamak');
insert into event (event_id, name, location) values (1095, 'Topcare Mucus Relief', 'Loangmaka');
insert into event (event_id, name, location) values (1096, 'Saniquat Foaming hand sanitizer', 'La Tebaida');
insert into event (event_id, name, location) values (1097, 'sunmark day time cold and cough', 'Taibai');
insert into event (event_id, name, location) values (1098, 'Renapath', 'Baiyan');
insert into event (event_id, name, location) values (1099, 'ALOMIDE', 'Changtian');
insert into event (event_id, name, location) values (1100, 'AZITHROMYCIN', 'Stavanger');
