use project_x;

delete from performance where id > 0 and dtype = 'sequence';

insert into performance (id, dtype, performer, title) values (1, 'sequence', 'cweatherhill0', 'Juice - Pineapple, 341 Ml');
insert into performance (id, dtype, performer, title) values (2, 'sequence', 'llawford1', 'Alize Sunset');
insert into performance (id, dtype, performer, title) values (3, 'sequence', 'gcruikshanks2', 'Bread - Corn Muffaletta');
insert into performance (id, dtype, performer, title) values (4, 'sequence', 'wgabbatt3', 'Veal - Insides, Grains');
insert into performance (id, dtype, performer, title) values (5, 'sequence', 'kmichin4', 'Tea - Jasmin Green');
insert into performance (id, dtype, performer, title) values (6, 'sequence', 'abeert5', 'Beer - Sleemans Cream Ale');
insert into performance (id, dtype, performer, title) values (7, 'sequence', 'mwoodson6', 'Tomato Puree');
insert into performance (id, dtype, performer, title) values (8, 'sequence', 'cjendrusch7', 'Wine - Mondavi Coastal Private');
insert into performance (id, dtype, performer, title) values (9, 'sequence', 'sextill8', 'Soup - Campbells, Cream Of');
insert into performance (id, dtype, performer, title) values (10, 'sequence', 'kmarling9', 'Tomatoes Tear Drop');
insert into performance (id, dtype, performer, title) values (11, 'sequence', 'flowriea', 'Wine - White, Cooking');
insert into performance (id, dtype, performer, title) values (12, 'sequence', 'blanehamb', 'Yoplait Drink');
insert into performance (id, dtype, performer, title) values (13, 'sequence', 'pjowseyc', 'Sauce - White, Mix');
insert into performance (id, dtype, performer, title) values (14, 'sequence', 'jpatyd', 'Napkin White');
insert into performance (id, dtype, performer, title) values (15, 'sequence', 'vchalfante', 'Yogurt - Cherry, 175 Gr');
insert into performance (id, dtype, performer, title) values (16, 'sequence', 'lwoodrooff', 'Squash - Guords');
insert into performance (id, dtype, performer, title) values (17, 'sequence', 'dmealiffeg', 'Halibut - Fletches');
insert into performance (id, dtype, performer, title) values (18, 'sequence', 'cantoninh', 'Chocolate Bar - Coffee Crisp');
insert into performance (id, dtype, performer, title) values (19, 'sequence', 'mbergstrami', 'Chips Potato Salt Vinegar 43g');
insert into performance (id, dtype, performer, title) values (20, 'sequence', 'dmccalisterj', 'Walkers Special Old Whiskey');
insert into performance (id, dtype, performer, title) values (21, 'sequence', 'cwolfarthk', 'Beer - Fruli');
insert into performance (id, dtype, performer, title) values (22, 'sequence', 'jbettisonl', 'Cassis');
insert into performance (id, dtype, performer, title) values (23, 'sequence', 'esanchism', 'Evaporated Milk - Skim');
insert into performance (id, dtype, performer, title) values (24, 'sequence', 'abransonn', 'Lamb - Leg, Diced');
insert into performance (id, dtype, performer, title) values (25, 'sequence', 'jgaveno', 'Cake Circle, Foil, Scallop');
insert into performance (id, dtype, performer, title) values (26, 'sequence', 'acritchellp', 'Muffin - Mix - Creme Brule 15l');
insert into performance (id, dtype, performer, title) values (27, 'sequence', 'jdinwoodieq', 'Coffee - 10oz Cup 92961');
insert into performance (id, dtype, performer, title) values (28, 'sequence', 'acarvillar', 'Hersey Shakes');
insert into performance (id, dtype, performer, title) values (29, 'sequence', 'ethreadgalls', 'Island Oasis - Raspberry');
insert into performance (id, dtype, performer, title) values (30, 'sequence', 'mgowryt', 'Parsnip');
insert into performance (id, dtype, performer, title) values (31, 'sequence', 'bmalshingeru', 'Truffle Cups - Brown');
insert into performance (id, dtype, performer, title) values (32, 'sequence', 'jbentamev', 'Cup Translucent 9 Oz');
insert into performance (id, dtype, performer, title) values (33, 'sequence', 'mfinlaterw', 'Beef - Cooked, Corned');
insert into performance (id, dtype, performer, title) values (34, 'sequence', 'nhaskerx', 'Thyme - Dried');
insert into performance (id, dtype, performer, title) values (35, 'sequence', 'navisony', 'Rambutan');
insert into performance (id, dtype, performer, title) values (36, 'sequence', 'akisarz', 'Pasta - Detalini, White, Fresh');
insert into performance (id, dtype, performer, title) values (37, 'sequence', 'otwell10', 'Mushroom - Porcini Frozen');
insert into performance (id, dtype, performer, title) values (38, 'sequence', 'rganley11', 'Sauce - Oyster');
insert into performance (id, dtype, performer, title) values (39, 'sequence', 'dseabrook12', 'Lemon Pepper');
insert into performance (id, dtype, performer, title) values (40, 'sequence', 'iromer13', 'Neckerchief Blck');
insert into performance (id, dtype, performer, title) values (41, 'sequence', 'jruthven14', 'Cheese - Cottage Cheese');
insert into performance (id, dtype, performer, title) values (42, 'sequence', 'hcastanares15', 'Rosemary - Primerba, Paste');
insert into performance (id, dtype, performer, title) values (43, 'sequence', 'jmacadam16', 'Longos - Lasagna Beef');
insert into performance (id, dtype, performer, title) values (44, 'sequence', 'ppoetz17', 'Cheese Cheddar Processed');
insert into performance (id, dtype, performer, title) values (45, 'sequence', 'casling18', 'Chicken - Breast, 5 - 7 Oz');
insert into performance (id, dtype, performer, title) values (46, 'sequence', 'lcheccucci19', 'Soup - Campbells, Cream Of');
insert into performance (id, dtype, performer, title) values (47, 'sequence', 'edeverell1a', 'Steamers White');
insert into performance (id, dtype, performer, title) values (48, 'sequence', 'jleile1b', 'Lamb - Leg, Bone In');
insert into performance (id, dtype, performer, title) values (49, 'sequence', 'idabnor1c', 'Wine - Shiraz Wolf Blass Premium');
insert into performance (id, dtype, performer, title) values (50, 'sequence', 'chelks1d', 'Pastry - Cherry Danish - Mini');
